# Generated by Django 6.0.3 on 2026-04-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_nhanvien_vi_tri_vl'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKyLich',
            fields=[
                ('ma_dk', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('ca_lam', models.CharField(max_length=20)),
                ('trang_thai', models.CharField(default='CHO_DUYET', max_length=20)),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='NghiPhep',
            fields=[
                ('ma_np', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('ly_do', models.TextField()),
                ('trang_thai', models.CharField(default='CHO_DUYET', max_length=20)),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
        ),
    ]
