# Generated by Django 6.0.3 on 2026-04-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_dangkylich_nghiphep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nghiphep',
            name='ma_nv',
        ),
        migrations.DeleteModel(
            name='DangKyLich',
        ),
        migrations.DeleteModel(
            name='NghiPhep',
        ),
    ]
