# Generated by Django 6.0.3 on 2026-04-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_nhanvien_vi_tri_vl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='tk_ngan_hang',
        ),
    ]
