# Generated by Django 6.0.3 on 2026-04-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_nhanvien_tk_ngan_hang'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichlamviec',
            options={'verbose_name': 'Lịch làm việc', 'verbose_name_plural': 'Lịch làm việc'},
        ),
        migrations.AlterUniqueTogether(
            name='lichlamviec',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lichlamviec',
            name='ma_nv',
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='ma_nv',
            field=models.ManyToManyField(related_name='lich_lam_viec', to='employees.nhanvien'),
        ),
    ]
