# Generated by Django 6.0.3 on 2026-04-20 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('schedules', '0002_alter_lichlamviec_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichlamviec',
            name='ma_chi_nhanh',
            field=models.ForeignKey(default='CN01', on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='branches.chinhanh'),
        ),
    ]
