# Generated by Django 6.0.3 on 2026-04-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_nhanvien_tk_ngan_hang'),
        ('schedules', '0003_alter_lichlamviec_ma_chi_nhanh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichlamviec',
            name='ma_nv',
        ),
        migrations.CreateModel(
            name='ChiTietLichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_tri', models.CharField(max_length=50, verbose_name='Vị trí làm việc')),
                ('ma_llv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.lichlamviec')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_llv', 'ma_nv')},
            },
        ),
    ]
