# Generated by Django 6.0.3 on 2026-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_nhanvien_tk_ngan_hang'),
        ('schedules', '0004_remove_lichlamviec_ma_nv_chitietlichlamviec'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichlamviec',
            name='ma_nv',
            field=models.ManyToManyField(related_name='lich_lam_viec', through='schedules.ChiTietLichLamViec', to='employees.nhanvien'),
        ),
    ]
