# Generated by Django 6.0.3 on 2026-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='trang_thai',
            field=models.CharField(default='Đang hoạt động', max_length=50),
        ),
    ]
